[[plugins]]
repo = 'Shougo/dein.vim'
[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'
[[plugins]]
repo = 'thinca/vim-template'
[[plugins]]
repo = 'kana/vim-submode'
[[plugins]]
repo = 'kana/vim-smartinput'
[[plugins]]
repo = 'Townk/vim-autoclose'

